### ISSUE TITLE
Is libs/base64-string.js used in this project?

### ISSUE THREAD

**Issue by isiahmeadows** [pieroxy/lz-string#100]
I just noticed that it [doesn't look referenced anywhere else](https://github.com/pieroxy/lz-string/search?utf8=%E2%9C%93&q=Base64String&type=).

**Comment by pieroxy** [comment]
It's just a piece of lib I wrote a while ago to store base64 representations of JPGs in localStorage. I don't really know what to do with it to be honest. It's somewhat useful though.

**Comment by rquadling** [comment]
If the code is useful, maybe put it into a gist and remove it from the lib.

Or put it into another directory within this project but exclude it from builds/main, etc.

**Comment by pieroxy** [comment]
Well, it serves the same purpose as lz-string does: Storing data in localStorage and other string-based storages. If the data you're storing is compressible (eg, json) you use lz-string, if the data you store is not compressible (eg a JPG image) you use base64-string.

So in my view, they are pretty much the same lib for two different use cases.

**Comment by isiahmeadows** [comment]
@pieroxy If you need to base64-encode/decode something:

- Browsers: There's [`window.btoa(str)`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa) for encoding, [`window.atob(encoded)`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob) for decoding.
- Node.js: [Buffers support multiple encodings, and `'base64'` is one of them](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings). Encoding is done via `Buffer.from(str).toString('base64')`, and decoding via `Buffer.from(str, 'base64').toString()`

I'm not convinced we need an *n*+1 version of each, especially in browsers which already natively implement them (as required by spec). In addition, Node.js not only supports base64 encoding, but it also has much better compression options anyways for 99.9% of use cases, shipped with the runtime itself.

**Comment by CodyKochmann** [comment]
It might be a little offhand to mention but, I've had pretty good compression gains come out of compressing b64 photos. Ill look to see if I still have the documentation I have on this but no promises that I'll find it. It's pretty easy to test though.

**Comment by pieroxy** [comment]
@CodyKochmann I know lz-string works on JPGs (in base64 for example), but you would have a much better ratio with base64-string.

@isiahmeadows you don't understand. The point of base64-string is to take a non-compressable input in base64 (for example a JPG) and store it into a much smaller string using 15 bits per character. That string will be much smaller and can be safely stored in localStorage or other client-side storage.

Much like LZ-String but specialized for non-compressable input. The thing is, LW-String is based on LZW which tends to produce an output that is bigger than the input when the input is already compressed.

So while LZ-String works in this scenario, base64-string will inevitably gives a much smaller output.

**Comment by isiahmeadows** [comment]
@pieroxy I think you missed my point: I'm not saying you should double-compress things like images (you shouldn't). I'm just saying it's pointless to duplicate (highly optimized) native functionality.

**Comment by pieroxy** [comment]
base64string has little to do with btoa and atob. base64string will take a string representing base64 and will produce another string smaller that contains the same data. That's all it does. And no, there is no such functionality built in any browser that I know of.

**Comment by isiahmeadows** [comment]
Okay...what's the difference?

**Comment by pieroxy** [comment]
`atob` and `btoa` convert from (and to) base64 to 8-bit per character representation of the binary data. Base64-string converts from base64 to 15-bit per character of the binary data, hence producing strings that are almost half the size as `window.atob`. They just serve a different purpose.

**Comment by isiahmeadows** [comment]
Oh okay. Then my point is invalid, since you leverage the fact JS character codes are 16-bit rather than ASCII's 7-bit format that Base64 uses.

(Nit: Base64 stores 6 bits per byte, not 8.)

**Comment by isiahmeadows** [comment]
I will caution: anything that requires an escape will dramatically adversely affect density, specifically `\u2028`, `\u2029`, and friends.

**Comment by pieroxy** [comment]
What? Strings are stored in UTF-16, which consumes 16 bits per character. By using 15 out of these 16 bits, we can greatly reduce the size occupied by our binary data. That is the whole point of these two libraries. I don't see how escape sequences affect this.

**Comment by isiahmeadows** [comment]
@pieroxy When sending certain character codes (like U+2028 in JS strings), you may have to encode them differently in order for them to be representable. In practice, this is unlikely to affect much (if the language supports non-ASCII code points), but it is a thing to take account in theory, as it's also possible to specifically encode something to cause issues (thus you have to treat the encoder's output as untrusted when interpolating it).

- JS: `\`, `"`, `'`, `\r`, `\n`, U+2028, and U+2029
- JSON: `\`, `"`, and any control code (U+0000 to U+001F)
- HTML5: space, `"`, `'`, `>`, `/`, `=`, any control code, the range U+FDD0 to U+FDEF, U+FFFE, and U+FFFF

Another item of note: you might want to give a high-level API overview in the README and put the link also in your repo's description, so it's easier for people to find the docs for it. (Currently, the only link is the last thing in the README, which isn't super helpful.)

**Comment by isiahmeadows** [comment]
Given that my issue has been addressed now, I'm going to go ahead and close this.

**Comment by joeyparis** [comment]
@pieroxy Sorry for re-opening such an old thread, but how would I go about importing `Base64String` from `lz-string` with ES6? I have a use case for it that I think I would benefit from.
