### ISSUE TITLE
Array size is not a small enough positive integer

### ISSUE THREAD

**Issue by RicoLiu** [pieroxy/lz-string#101]
Hey, I am facing a problem. Use **compressToUint8Array** method.

**compressed sample is :** 54,132,96,76,14,192,52,237,179,144,93,31,84,189,204,211,182,174,231,24,23,161,250,146,121,198,84,117,101,91,77,20,55,99,246,178,251,206,116,247,109,123,207,28,5,244,31,212,72,241,195,37,14,150,42,108,153,18,21,204,95,53,74,245,203,53,46,214,171,110,157,26,13,236,63,180,201,243,199,140,0,224,67,124,29,176,14,158,217,127,117,227,247,206,223,120,243,235,239,128,255,32,207,16,191,80,192,240,224,176,232,136,152,168,216,132,248,248,128,78,4,84,144,0,102,0,6,24,108,220,156,204,130,188,194,252,210,204,144,92,138,242,202,154,204,140,220,128,22,70,230,204,166,214,150,140,182,140,128,86,92,222,204,254,158,132,42,128,54,54,145,254,177,152,41,144,25,185,241,133,233,130,238,176,24,6,170,143,17,213,169,238,232,6,166,226,213,156,227,168,19,147,144,8,126,171,56,100,145,168,48,44,213,135,187,176,16,10,215,166,215,222,175,251,217,223,151,139,175,198,198,0,121,3,254,191,111,166,87,238,242,202,164,30,192,172,139,209,31,114,203,125,81,40,182,178,74,165,137,131,36,10,151,105,191,91,174,150,235,212,64,13,59,187,92,5,87,36,192,222,48,44,133,76,234,113,100,157,122,112,2,139,192,234,181,64,100,170,25,30,64,183,38,72,202,82,26,5,125,154,196,158,53,25,216,32,159,88,111,199,42,246,84,129,149,138,135,156,43,32,136,71,65,158,40,178,114,78,204,147,104,130,16,5,16,58,68,7,102,181,210,224,128,183,191,86,150,243,39,128,233,52,154,125,171,215,107,166,82,254,142,186,91,68,4,234,117,251,237,14,126,152,18,57,29,54,154,201,102,234,121,174,149,105,180,219,234,70,168,21,137,165,96,169,88,114,16,59,129,40,180,215,149,64,32,245,8,52,2,3,99,205,64,51,106,130,150,76,156,139,85,90,121,193,159,91,198,222,149,5,188,83,153,154,244,10,203,214,30,102,71,119,107,128,243,58,145,199,37,211,77,91,130,20,215,6,41,13,201,18,182,131,68,153,52,231,141,41,35,116,132,7,153,89,128,158,46,148,130,233,226,247,3,62,222,47,23,254,129,34,233,51,37,204,229,109,106,233,238,85,86,234,111,250,146,242,95,243,21,210,6,142,5,2,214,48,44,11,20,197,127,211,115,130,214,77,204,144,2,26,30,93,101,201,210,12,142,192,200,87,28,55,37,195,50,44,43,9,93,41,4,213,226,76,251,58,70,215,180,157,87,93,178,169,181,6,95,162,109,51,33,200,113,29,234,90,194,5,73,63,19,215,138,172,107,28,138,193,20,186,65,133,116,35,208,190,143,13,200,236,20,45,98,66,69,12,48,81,20,100,137,85,13,67,255,127,198,73,146,64,157,38,6,233,41,110,136,147,104,86,61,34,83,3,255,65,67,12,164,249,2,2,180,45,217,18,213,98,60,203,28,128,242,128,220,145,134,192,243,82,111,51,48,157,160,60,78,181,89,146,94,158,180,100,25,54,139,39,180,45,118,201,214,220,244,163,47,75,37,186,31,194,81,146,197,77,195,96,112,48,193,128,163,0,48,145,68,84,21,5,34,136,161,2,236,19,56,49,229,244,223,142,19,1,234,16,91,228,64,65,56,79,33,5,129,48,19,229,5,94,0,70,20,53,6,43,35,167,228,242,158,199,183,136,72,200,217,180,139,155,30,81,224,100,114,100,128,47,77,4,154,221,140,205,243,110,53,34,177,86,81,202,193,177,2,228,152,40,93,41,69,77,224,180,45,100,12,146,124,184,152,27,109,186,218,44,222,237,186,201,59,186,215,196,229,67,194,244,229,70,78,87,234,89,254,224,196,145,36,42,184,6,174,13,140,164,47,243,89,160,181,131,72,67,225,242,85,10,40,176,235,50,54,32,72,215,70,209,162,233,70,195,148,139,232,198,220,236,13,59,50,60,5,52,176,193,64,107,89,80,208,103,244,138,118,222,132,96,169,186,28,130,146,128,50,84,131,154,128,208,134,158,165,231,185,166,146,80,3,78,181,78,149,139,147,37,213,192,201,148,185,58,27,89,180,225,146,140,237,253,14,205,226,13,93,122,61,34,138,25,19,164,234,117,219,87,73,215,180,123,30,83,168,64,72,228,3,15,228,69,3,34,168,171,129,189,32,200,135,29,132,181,222,13,146,137,71,40,147,201,3,39,242,169,144,168,124,151,131,201,127,98,81,26,202,27,58,162,143,35,152,239,40,113,144,18,52,215,109,147,177,110,149,117,93,32,196,51,164,179,128,215,62,117,243,204,251,58,46,243,156,245,91,47,67,37,109,7,142,8,88,205,36,146,8,234,118,92,71,114,49,95,220,134,17,128,227,186,66,212,181,159,223,247,80,153,42,8,239,249,12,37,116,24,186,34,182,164,143,242,186,252,3,27,220,116,97,1,140,16,120,195,96,180,61,119,83,123,120,105,20,229,211,79,247,181,120,185,87,11,174,210,94,241,87,126,88,111,112,45,90,44,161,158,124,81,162,61,42,167,203,247,38,42,223,187,250,191,1,38,132,20,216,180,173,126,198,241,189,41,241,1,182,130,139,128,222,201,2,54,6,197,54,166,222,51,198,104,196,189,205,129,6,202,179,222,250,174,34,143,201,77,134,17,18,222,223,154,1,57,99,237,97,189,119,64,36,76,81,135,53,129,41,251,163,118,110,228,157,184,16,134,22,205,201,24,17,30,82,64,96,127,18,131,224,19,153,247,170,43,215,251,240,196,206,0,242,176,143,34,80,49,91,128,88,16,35,120,120,7,140,166,145,7,127,100,30,0,200,98,143,32,94,3,5,223,71,231,16,56,80,163,168,189,194,10,207,24,234,253,163,166,9,126,83,221,250,232,160,225,221,131,178,18,66,172,51,33,143,14,130,40,54,45,115,38,60,57,122,184,143,22,109,60,92,138,65,74,37,68,91,5,12,162,252,112,75,0,36,83,71,160,231,231,60,208,87,247,64,46,43,198,139,86,192,200,173,13,37,46,61,158,5,240,153,17,147,164,104,73,81,150,194,59,91,14,136,49,172,177,73,110,190,42,49,184,178,153,24,130,78,73,9,1,44,130,160,168,152,211,239,179,79,9,173,58,37,160,140,41,19,212,116,114,49,134,54,160,212,129,151,128,215,26,23,92,179,223,57,209,45,230,233,56,95,76,200,230,39,71,75,97,72,178,44,103,71,174,162,148,165,82,121,151,28,24,4,211,41,113,33,6,84,158,23,18,227,22,79,73,222,32,228,40,139,158,83,46,124,138,185,183,58,167,89,43,233,194,90,100,64,32,247,32,129,229,120,192,85,180,96,165,233,38,39,167,104,144,37,66,104,108,149,161,32,188,83,123,108,42,178,74,168,137,17,224,50,210,87,7,66,172,157,58,181,78,111,22,104,45,25,192,20,238,8,83,172,11,129,115,166,96,161,81,103,17,40,90,118,11,34,54,89,169,20,78,135,33,180,235,210,100,111,109,234,139,233,32,141,92,216,32,71,140,226,98,3,73,189,241,74,122,79,217,242,189,45,85,170,178,86,50,68,136,144,25,80,97,85,18,187,180,21,2,184,50,123,41,79,45,21,121,33,36,203,7,242,131,3,32,101,165,105,37,149,193,149,41,42,230,28,67,44,70,204,42,75,33,100,108,162,150,194,185,166,68,5,122,40,134,48,192,233,221,237,83,15,2,42,174,85,131,45,140,11,232,75,172,178,148,47,214,140,128,210,50,131,64,240,53,174,172,52,89,8,80,227,150,86,81,192,240,174,20,0,137,111,26,97,114,108,17,220,186,4,166,222,199,26,179,79,99,202,48,42,70,156,175,24,90,11,124,101,54,52,135,55,136,196,91,173,38,119,101,17,146,51,36,72,172,151,19,114,169,142,89,184,51,35,89,98,42,178,39,173,70,101,9,33,38,157,1,214,74,135,67,35,37,90,202,209,19,61,233,58,11,167,46,157,135,206,119,151,95,66,76,224,99,104,169,33,56,65,4,235,84,26,138,59,103,180,19,49,150,231,72,22,163,183,118,141,53,22,189,102,97,127,84,27,189,100,103,158,100,13,229,152,110,29,115,14,115,235,57,79,178,231,16,36,132,96,80,64,128,166,108,40,54,33,26,22,184,188,90,227,89,236,57,102,79,89,146,122,205,105,233,89,1,186,214,66,246,209,208,126,123,75,64,59,51,198,200,213,219,115,220,97,110,57,245,187,39,198,92,222,35,72,157,111,195,43,175,12,22,134,145,18,159,181,26,105,183,160,35,32,82,212,71,227,22,22,18,171,36,166,33,176,50,6,48,173,172,13,125,216,22,161,62,55,7,71,162,110,205,162,61,54,166,146,57,38,178,125,239,80,49,57,130,49,161,22,38,136,201,24,195,239,161,121,148,186,154,184,100,172,23,245,53,33,118,231,115,82,7,216,194,25,51,88,91,141,224,138,18,29,253,124,30,178,93,25,13,52,228,13,135,112,194,100,69,225,145,53,136,137,63,154,178,73,26,169,185,61,194,104,238,152,23,34,115,79,240,55,44,45,148,149,207,200,186,15,103,11,111,176,103,248,132,186,65,131,127,30,5,161,218,73,66,141,19,92,95,97,109,139,119,49,44,12,236,59,151,124,200,73,185,50,122,201,41,51,93,219,32,245,93,142,40,97,34,194,238,84,114,24,60,66,25,172,115,140,118,139,55,106,193,64,155,181,214,184,141,72,188,208,219,83,120,158,229,13,98,210,166,4,92,3,17,68,218,77,16,33,172,141,229,217,226,234,122,7,240,157,44,197,254,205,193,84,21,64,106,185,149,177,118,166,156,24,82,216,213,171,18,16,167,143,37,154,183,149,144,51,152,83,144,63,248,137,153,189,202,84,201,201,123,120,105,174,92,207,213,195,191,109,31,91,22,62,45,176,44,47,248,144,156,48,110,23,44,7,204,193,69,208,161,209,223,107,231,191,8,94,171,51,106,173,96,197,54,14,17,59,178,171,77,68,103,88,96,69,61,144,111,100,159,23,23,170,106,216,49,93,55,167,147,150,219,6,169,213,92,51,246,118,172,253,134,119,27,250,210,222,251,51,58,120,197,197,26,102,240,117,13,5,242,73,185,130,187,16,142,192,107,159,219,42,207,208,227,208,19,90,230,217,25,195,231,32,103,45,143,223,230,58,114,184,103,207,43,236,149,168,61,86,244,253,162,12,186,232,248,246,119,180,102,225,213,171,51,93,117,10,110,49,70,5,6,167,27,179,253,46,142,62,219,156,231,246,90,233,121,15,197,93,81,227,23,86,29,211,186,145,82,104,109,221,140,216,70,240,249,95,75,136,228,101,83,200,113,209,161,198,206,143,84,240,98,90,251,21,214,210,226,124,227,108,173,2,70,63,238,68,179,68,185,23,64,57,89,77,183,59,55,32,89,95,203,213,55,45,196,203,0,33,138,222,159,78,251,96,62,166,213,59,46,93,218,3,91,53,109,172,129,211,180,142,187,252,24,194,14,24,183,101,220,178,94,66,127,123,123,152,122,166,43,198,148,23,242,111,223,153,48,125,188,1,195,95,43,149,86,228,3,168,253,77,87,50,128,208,128,161,9,117,150,255,70,47,134,133,165,149,75,53,50,24,244,93,6,61,223,218,199,82,73,191,137,44,234,227,247,63,55,148,235,216,39,60,45,166,171,255,8,188,226,207,247,35,210,121,173,75,36,97,223,84,101,89,120,241,0,243,214,51,8,15,89,27,21,75,8,84,7,51,80,216,30,196,115,12,151,211,49,117,23,41,177,155,97,112,192,135,2,15,39,181,247,111,51,192,255,116,91,21,183,8,47,244,119,124,15,247,50,209,157,93,226,153,85,102,229,70,246,92,21,116,51,81,36,235,80,87,252,48,32,86,37,243,213,93,80,143,109,20,121,122,53,121,21,22,175,7,150,249,104,50,143,49,9,53,51,83,95,84,52,16,185,114,43,108,181,54,46,135,228,14,176,227,98,130,205,82,226,54,1,16,71,30,241,96,139,179,5,107,215,223,67,243,53,45,151,79,23,245,187,53,224,205,122,12,195,82,183,203,102,6,176,218,149,47,27,9,160,122,119,224,141,116,83,80,23,23,52,8,69,7,0,216,106,149,111,54,112,167,105,148,19,61,15,231,71,80,95,48,83,42,100,116,155,101,98,151,15,53,192,209,245,125,44,210,192,175,14,72,188,244,151,7,247,247,70,246,175,100,1,39,85,112,11,34,130,66,13,199,231,72,247,173,92,240,116,72,18,113,25,243,159,81,9,143,99,177,79,77,151,112,52,50,111,108,147,247,102,119,175,54,139,27,64,244,232,207,18,200,133,1,72,3,23,135,78,215,249,104,227,153,44,18,89,112,86,153,46,150,11,79,180,72,41,100,239,45,15,18,80,114,208,193,137,3,26,114,32,179,10,232,216,143,199,34,14,96,63,12,152,154,49,11,1,15,176,177,7,31,38,0,0,93,32,0,0

**fetch data is:** 54,132,96,76,14,192,52,237,179,144,93,31,84,189,204,211,182,174,231,24,23,161,250,146,121,198,84,117,101,91,77,20,55,99,246,178,251,206,116,247,109,123,207,28,5,244,31,212,72,241,195,37,14,150,42,108,153,18,21,204,95,53,74,245,203,53,46,214,171,110,157,26,13,236,63,180,201,243,199,140,0,224,67,124,29,176,14,158,217,127,117,227,247,206,223,120,243,235,239,128,255,32,207,16,191,80,192,240,224,176,232,136,152,168,216,132,248,248,128,78,4,84,144,0,102,0,6,24,108,220,156,204,130,188,194,252,210,204,144,92,138,242,202,154,204,140,220,128,22,70,230,204,166,214,150,140,182,140,128,86,92,222,204,254,158,132,42,128,54,54,145,254,177,152,41,144,25,185,241,133,233,130,238,176,24,6,170,143,17,213,169,238,232,6,166,226,213,156,227,168,19,147,144,8,126,171,56,100,145,168,48,44,213,135,187,176,16,10,215,166,215,222,175,251,217,223,151,139,175,198,198,0,121,3,254,191,111,166,87,238,242,202,164,30,192,172,139,209,31,114,203,125,81,40,182,178,74,165,137,131,36,10,151,105,191,91,174,150,235,212,64,13,59,187,92,5,87,36,192,222,48,44,133,76,234,113,100,157,122,112,2,139,192,234,181,64,100,170,25,30,64,183,38,72,202,82,26,5,125,154,196,158,53,25,216,32,159,88,111,199,42,246,84,129,149,138,135,156,43,32,136,71,65,158,40,178,114,78,204,147,104,130,16,5,16,58,68,7,102,181,210,224,128,183,191,86,150,243,39,128,233,52,154,125,171,215,107,166,82,254,142,186,91,68,4,234,117,251,237,14,126,152,18,57,29,54,154,201,102,234,121,174,149,105,180,219,234,70,168,21,137,165,96,169,88,114,16,59,129,40,180,215,149,64,32,245,8,52,2,3,99,205,64,51,106,130,150,76,156,139,85,90,121,193,159,91,198,222,149,5,188,83,153,154,244,10,203,214,30,102,71,119,107,128,243,58,145,199,37,211,77,91,130,20,215,6,41,13,201,18,182,131,68,153,52,231,141,41,35,116,132,7,153,89,128,158,46,148,130,233,226,247,3,62,222,47,23,254,129,34,233,51,37,204,229,109,106,233,238,85,86,234,111,250,146,242,95,243,21,210,6,142,5,2,214,48,44,11,20,197,127,211,115,130,214,77,204,144,2,26,30,93,101,201,210,12,142,192,200,87,28,55,37,195,50,44,43,9,93,41,4,213,226,76,251,58,70,215,180,157,87,93,178,169,181,6,95,162,109,51,33,200,113,29,234,90,194,5,73,63,19,215,138,172,107,28,138,193,20,186,65,133,116,35,208,190,143,13,200,236,20,45,98,66,69,12,48,81,20,100,137,85,13,67,255,127,198,73,146,64,157,38,6,233,41,110,136,147,104,86,61,34,83,3,255,65,67,12,164,249,2,2,180,45,217,18,213,98,60,203,28,128,242,128,220,145,134,192,243,82,111,51,48,157,160,60,78,181,89,146,94,158,180,100,25,54,139,39,180,45,118,201,214,220,244,163,47,75,37,186,31,194,81,146,197,77,195,96,112,48,193,128,163,0,48,145,68,84,21,5,34,136,161,2,236,19,56,49,229,244,223,142,19,1,234,16,91,228,64,65,56,79,33,5,129,48,19,229,5,94,0,70,20,53,6,43,35,167,228,242,158,199,183,136,72,200,217,180,139,155,30,81,224,100,114,100,128,47,77,4,154,221,140,205,243,110,53,34,177,86,81,202,193,177,2,228,152,40,93,41,69,77,224,180,45,100,12,146,124,184,152,27,109,186,218,44,222,237,186,201,59,186,215,196,229,67,194,244,229,70,78,87,234,89,254,224,196,145,36,42,184,6,174,13,140,164,47,243,89,160,181,131,72,67,225,242,85,10,40,176,235,50,54,32,72,215,70,209,162,233,70,195,148,139,232,198,220,236,13,59,50,60,5,52,176,193,64,107,89,80,208,103,244,138,118,222,132,96,169,186,28,130,146,128,50,84,131,154,128,208,134,158,165,231,185,166,146,80,3,78,181,78,149,139,147,37,213,192,201,148,185,58,27,89,180,225,146,140,237,253,14,205,226,13,93,122,61,34,138,25,19,164,234,117,219,87,73,215,180,123,30,83,168,64,72,228,3,15,228,69,3,34,168,171,129,189,32,200,135,29,132,181,222,13,146,137,71,40,147,201,3,39,242,169,144,168,124,151,131,201,127,98,81,26,202,27,58,162,143,35,152,239,40,113,144,18,52,215,109,147,177,110,149,117,93,32,196,51,164,179,128,215,62,117,243,204,251,58,46,243,156,245,91,47,67,37,109,7,142,8,88,205,36,146,8,234,118,92,71,114,49,95,220,134,17,128,227,186,66,212,181,159,223,247,80,153,42,8,239,249,12,37,116,24,186,34,182,164,143,242,186,252,3,27,220,116,97,1,140,16,120,195,96,180,61,119,83,123,120,105,20,229,211,79,247,181,120,185,87,11,174,210,94,241,87,126,88,111,112,45,90,44,161,158,124,81,162,61,42,167,203,247,38,42,223,187,250,191,1,38,132,20,216,180,173,126,198,241,189,41,241,1,182,130,139,128,222,201,2,54,6,197,54,166,222,51,198,104,196,189,205,129,6,202,179,222,250,174,34,143,201,77,134,17,18,222,223,154,1,57,99,237,97,189,119,64,36,76,81,135,53,129,41,251,163,118,110,228,157,184,16,134,22,205,201,24,17,30,82,64,96,127,18,131,224,19,153,247,170,43,215,251,240,196,206,0,242,176,143,34,80,49,91,128,88,16,35,120,120,7,140,166,145,7,127,100,30,0,200,98,143,32,94,3,5,223,71,231,16,56,80,163,168,189,194,10,207,24,234,253,163,166,9,126,83,221,250,232,160,225,221,131,178,18,66,172,51,33,143,14,130,40,54,45,115,38,60,57,122,184,143,22,109,60,92,138,65,74,37,68,91,5,12,162,252,112,75,0,36,83,71,160,231,231,60,208,87,247,64,46,43,198,139,86,192,200,173,13,37,46,61,158,5,240,153,17,147,164,104,73,81,150,194,59,91,14,136,49,172,177,73,110,190,42,49,184,178,153,24,130,78,73,9,1,44,130,160,168,152,211,239,179,79,9,173,58,37,160,140,41,19,212,116,114,49,134,54,160,212,129,151,128,215,26,23,92,179,223,57,209,45,230,233,56,95,76,200,230,39,71,75,97,72,178,44,103,71,174,162,148,165,82,121,151,28,24,4,211,41,113,33,6,84,158,23,18,227,22,79,73,222,32,228,40,139,158,83,46,124,138,185,183,58,167,89,43,233,194,90,100,64,32,247,32,129,229,120,192,85,180,96,165,233,38,39,167,104,144,37,66,104,108,149,161,32,188,83,123,108,42,178,74,168,137,17,224,50,210,87,7,66,172,157,58,181,78,111,22,104,45,25,192,20,238,8,83,172,11,129,115,166,96,161,81,103,17,40,90,118,11,34,54,89,169,20,78,135,33,180,235,210,100,111,109,234,139,233,32,141,92,216,32,71,140,226,98,3,73,189,241,74,122,79,217,242,189,45,85,170,178,86,50,68,136,144,25,80,97,85,18,187,180,21,2,184,50,123,41,79,45,21,121,33,36,203,7,242,131,3,32,101,165,105,37,149,193,149,41,42,230,28,67,44,70,204,42,75,33,100,108,162,150,194,185,166,68,5,122,40,134,48,192,233,221,237,83,15,2,42,174,85,131,45,140,11,232,75,172,178,148,47,214,140,128,210,50,131,64,240,53,174,172,52,89,8,80,227,150,86,81,192,240,174,20,0,137,111,26,97,114,108,17,220,186,4,166,222,199,26,179,79,99,202,48,42,70,156,175,24,90,11,124,101,54,52,135,55,136,196,91,173,38,119,101,17,146,51,36,72,172,151,19,114,169,142,89,184,51,35,89,98,42,178,39,173,70,101,9,33,38,157,1,214,74,135,67,35,37,90,202,209,19,61,233,58,11,167,46,157,135,206,119,151,95,66,76,224,99,104,169,33,56,65,4,235,84,26,138,59,103,180,19,49,150,231,72,22,163,183,118,141,53,22,189,102,97,127,84,27,189,100,103,158,100,13,229,152,110,29,115,14,115,235,57,79,178,231,16,36,132,96,80,64,128,166,108,40,54,33,26,22,184,188,90,227,89,236,57,102,79,89,146,122,205,105,233,89,1,186,214,66,246,209,208,126,123,75,64,59,51,198,200,213,219,115,220,97,110,57,245,187,39,198,92,222,35,72,157,111,195,43,175,12,22,134,145,18,159,181,26,105,183,160,35,32,82,212,71,227,22,22,18,171,36,166,33,176,50,6,48,173,172,13,125,216,22,161,62,55,7,71,162,110,205,162,61,54,166,146,57,38,178,125,239,80,49,57,130,49,161,22,38,136,201,24,195,239,161,121,148,186,154,184,100,172,23,245,53,33,118,231,115,82,7,216,194,25,51,88,91,141,224,138,18,29,253,124,30,178,93,25,13,52,228,13,135,112,194,100,69,225,145,53,136,137,63,154,178,73,26,169,185,61,194,104,238,152,23,34,115,79,240,55,44,45,148,149,207,200,186,15,103,11,111,176,103,248,132,186,65,131,127,30,5,161,218,73,66,141,19,92,95,97,109,139,119,49,44,12,236,59,151,124,200,73,185,50,122,201,41,51,93,219,32,245,93,142,40,97,34,194,238,84,114,24,60,66,25,172,115,140,118,139,55,106,193,64,155,181,214,184,141,72,188,208,219,83,120,158,229,13,98,210,166,4,92,3,17,68,218,77,16,33,172,141,229,217,226,234,122,7,240,157,44,197,254,205,193,84,21,64,106,185,149,177,118,166,156,24,82,216,213,171,18,16,167,143,37,154,183,149,144,51,152,83,144,63,248,137,153,189,202,84,201,201,123,120,105,174,92,207,213,195,191,109,31,91,22,62,45,176,44,47,248,144,156,48,110,23,44,7,204,193,69,208,161,209,223,107,231,191,8,94,171,51,106,173,96,197,54,14,17,59,178,171,77,68,103,88,96,69,61,144,111,100,159,23,23,170,106,216,49,93,55,167,147,150,219,6,169,213,92,51,246,118,172,253,134,119,27,250,210,222,251,51,58,120,197,197,26,102,240,117,13,5,242,73,185,130,187,16,142,192,107,159,219,42,207,208,227,208,19,90,230,217,25,195,231,32,103,45,143,223,230,58,114,184,103,207,43,236,149,168,61,86,244,253,162,12,186,232,248,246,119,180,102,225,213,171,51,93,117,10,110,49,70,5,6,167,27,179,253,46,142,62,219,156,231,246,90,233,121,15,197,93,81,227,23,86,29,211,186,145,82,104,109,221,140,216,70,240,249,95,75,136,228,101,83,200,113,209,161,198,206,143,84,240,98,90,251,21,214,210,226,124,227,108,173,2,70,63,238,68,179,68,185,23,64,57,89,77,183,59,55,32,89,95,203,213,55,45,196,203,0,33,138,222,159,78,251,96,62,166,213,59,46,93,218,3,91,53,109,172,129,211,180,142,187,252,24,194,14,24,183,101,220,178,94,66,127,123,123,152,122,166,43,198,148,23,242,111,223,153,48,125,188,1,195,95,43,149,86,228,3,168,253,77,87,50,128,208,128,161,9,117,150,255,70,47,134,133,165,149,75,53,50,24,244,93,6,61,223,218,199,82,73,191,137,44,234,227,247,63,55,148,235,216,39,60,45,166,171,255,8,188,226,207,247,35,210,121,173,75,36,97,223,84,101,89,120,241,0,243,214,51,8,15,89,27,21,75,8,84,7,51,80,216,30,196,115,12,151,211,49,117,23,41,177,155,97,112,192,135,2,15,39,181,247,111,51,192,255,116,91,21,183,8,47,244,119,124,15,247,50,209,157,93,226,153,85,102,229,70,246,92,21,116,51,81,36,235,80,87,252,48,32,86,37,243,213,93,80,143,109,20,121,122,53,121,21,22,175,7,150,249,104,50,143,49,9,53,51,83,95,84,52,16,185,114,43,108,181,54,46,135,228,14,176,227,98,130,205,82,226,54,1,16,71,30,241,96,139,179,5,107,215,223,67,243,53,45,151,79,23,245,187,53,224,205,122,12,195,82,183,203,102,6,176,218,149,47,27,9,160,122,119,224,141,116,83,80,23,23,52,8,69,7,0,216,106,149,111,54,112,167,105,148,19,61,15,231,71,80,95,48,83,42,100,116,155,101,98,151,15,53,192,209,245,125,44,210,192,175,14,72,188,244,151,7,247,247,70,246,175,100,1,39,85,112,11,34,130,66,13,199,231,72,247,173,92,240,116,72,18,113,25,243,159,81,9,143,99,177,79,77,151,112,52,50,111,108,147,247,102,119,175,54,139,27,64,244,232,207,18,200,133,1,72,3,23,135,78,215,249,104,227,153,44,18,89,112,86,153,46,150,11,79,180,72,41,100,239,45,15,18,80,114,208,193,137,3,26,114,32,179,10,232,216,143,199,34,14,96,63,12,152,154,49,11,1,15,176,177,7,31,38,0,0,93,32,0,0

I fetch this data from db, and use **decompressFromUint8Array** method.

This error at lz-string: 76.

version: 1.4.5

What is wrong?

**Comment by pieroxy** [comment]
Can you give me the original string that was compressed?

**Comment by RicoLiu** [comment]
oh...I have solved it. Due to the type of the parameter...
