### ISSUE TITLE
can you provide a c-language version ?

### ISSUE THREAD

**Issue by Ignorances** [pieroxy/lz-string#103]
I am very lucky to find this lib,but is should use it both in the js and c++ at my development.
I found only a QT version lib as your reference. it can not gain a fastest process speed ..

**Comment by pieroxy** [comment]
Unfortunately I don't have nearly enough time to maintain the JS version, so I will not be able to write a C++ version.

However, it is simple enough. Follow my advices here http://pieroxy.net/blog/pages/lz-string/index.html#inline_menu_7

Back in the days I ported it to go with a friend and it took the best of a couple of hours to do so.
