### ISSUE TITLE
Lz-string ugly outcome broken in server side and unable to decompress on java side

### ISSUE THREAD

**Issue by Prabh2k7** [pieroxy/lz-string#104]
I think what @joeshae facing is still exist in LZString side.
Fyi below are the problem I am facing and I am desperate to find the solution.

I have following (ugly)characters. And I am trying to send this from client(Javascript) side to server(Java). Following are the image data as "compressed" I am sending to server.
java script code:
```
function callServer() {
	    debugger;
	    var compressed = LZString.compress('/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk');
	    alert('compressed : '+compressed);
	    var formData = "img="+compressed;
	        jQuery.ajax({
	                url : "/RegisterServlet/servlet/Register",
	            type: "POST",
	            data : formData,
	            cache: false,
	            async:false,
	            success: function() {
	            },
	            error: function (){
	            }
	          });       
	     }

```

Java code
------------------
```
public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
{
    request.setCharacterEncoding(encoding);
    String compressedData = request.getParameter("img");
    String decompress = LZString.decompress(compressedData);
}
```

As per above code, I can able to receive the input I sent from script side to java as compressedData as follow : received broken/changes chars

But As you can see the red marked item on above attachment some of the images I sent are broken or become "?" mark or some different looks.

But I require to get the exact image data which sent?
Fyr, the input and output:

![brokenimages](https://user-images.githubusercontent.com/31923375/30376781-255c9188-98ab-11e7-8493-30b51691a4af.PNG)
![uglychars](https://user-images.githubusercontent.com/31923375/30376780-2554dcea-98ab-11e7-8854-bbc39ba7a334.PNG)

**Comment by rquadling** [comment]
Can you hex dump both sets of data. That's a better comparison. Or and md5 hash.

**Comment by Prabh2k7** [comment]
I did found a solution as follow for this case : 

 This can be done by mentioning UTF-8 encode by follow:

in server.xml under config:
`Connector port="8080" protocol="HTTP/1.1 connectionTimeout="20000" redirectPort="8443" URIEncoding="UTF-8
`In HTML/JSP :
[meta content="text/html; charset=UTF-8" http-equiv="Content-Type](url)

3.mentioning in java action class in the beginning:
[request.setCharacterEncoding("utf-8");](url)

Most importantly compress/decompress is not working for this. I have used compressToUTF16/decompressFromUTF16. This getting outcome as UTF16 only works!

**Comment by pieroxy** [comment]
Yes, as mentionned in the documentation, `compress` produces output that is *not* UTF-16 compatible, so implementations can/will garble the string since it does not respect basic UTF principles. For example, storing such a String in `localStorage` often results in a garbled string when read later on in Firecof and IE.
