### ISSUE TITLE
Update release version number

### ISSUE THREAD

**Issue by gRoussac** [pieroxy/lz-string#105]
Hi,

I believe you have been modifying a file in this commit https://github.com/pieroxy/lz-string/commit/c58a22021000ac2d99377cc0bf9ac193a12563c5 but without incrementing the version of your plugin. So CDNs in the wild are hosting a file which is supposed to be an 1.4.4 and it is while your master is serving another file with the same version number. Took me quite some time to figure that out. 

I would highly recommend that you implement a dev/master merged branches strategy and issue a new version number when merging in master branch. 

Otherwise this is the kind of thing that might break internet one day. Thanks for your help.

**Comment by gRoussac** [comment]
Hey,

I believe you also forgot to update this file accordingly https://github.com/pieroxy/lz-string/blob/master/libs/lz-string.min.js no angular export in it.

**Comment by pieroxy** [comment]
So, you're telling me CDNs just ignore the notiong of a GIT release and rely exclusively on `bower.json` or `package.json` ?

Good to know.

Anyways, I'm going to fix this soon. Thanks for the heads up.

**Comment by gRoussac** [comment]
Hey,

I think there might be a misunderstanding. The hosted file on CDN is your 1.4.4 released tag. But your master branch seems to be a 1.4.4 version too, so to me it s confusing. Maybe I am wrong and we are supposed to understand that your matser branch is not iso to your last tag, which is usually the case on other projects.

Success and thanks again for your work on this plugin, have a good day.

**Comment by pieroxy** [comment]
Ah, I see what you mean. I will create a new version soon anyways. Thanks !

**Comment by studioTeaTwo** [comment]
yarn registry, too.
It seem to be v1.4.3.

`https://registry.yarnpkg.com/lz-string/-/lz-string-1.4.4.tgz#c0d8eaf36059f705796e1e344811cf4c498d3a26`

**Comment by Rycochet** [comment]
Should be correct now
