### ISSUE TITLE
Update CLI bin.js to support optional arguments

### ISSUE THREAD

**Issue by user123412** [pieroxy/lz-string#107]
Please can you update the [CLI bin.js functionality](https://github.com/pieroxy/lz-string/blob/master/bin/bin.js) to support the user supplying arguments for the same set of functions as exposed by [lz-string.js](https://github.com/pieroxy/lz-string/blob/master/libs/lz-string.js), both for compressing and decompressing? Currently you can only do

`$ lz-string input.js > output.txt`

But you could improve the functionality to have e.g.

`$ lz-string --decompressFromBase64 b64compressed_input.txt > decompressed_output.txt`

Thank you

**Comment by Rycochet** [comment]
New CLI supports far more arguments, see details in the README!
