### ISSUE TITLE
Decompression of Uint8Array string saved to file cannot be decompressed

### ISSUE THREAD

**Issue by JarolinVargas** [pieroxy/lz-string#111]
I compress a string with LZString.compressToUint8Array(string) and save the result to a file that is downloaded to the user's computer. That same file uploaded to my web app via input file cannot be decompressed by taking the contents of the file(compressed), and decompressing with decompressFromUTF8(filecontent). I get the following console error: `Uncaught Error: Syntax error, unrecognized expression:  " ���P(�`��|C	�(�!�v����Qh...`

**Comment by rquadling** [comment]
The methods come in pairs. Compress/Decompress. Use the right one.
https://github.com/pieroxy/lz-string/blob/master/typings/lz-string.d.ts

**Comment by JarolinVargas** [comment]
That's actually what I'm using. but it's still not working
`LZString.compressToUint8Array(string)`
`LZString.decompressFromUint8Array(compressed)`

**Comment by Rycochet** [comment]
Closing this in favour of #139 - the comments on here don't hit on the solution and the slightly newer issue got my comment first! (we have reproducible code in the commandline tool and is easily demonstrated in the test script)
