### ISSUE TITLE
Sendind the result of `.compress()` as text/plaing

### ISSUE THREAD

**Issue by ivanquirino** [pieroxy/lz-string#115]
Can I send the result of `.compress()` as text/plain int the body of a POST or PUT request, decompress it on the server? Or do I need to use the base64 or URI methods?

Thanks

**Comment by JobLeonard** [comment]
On the [LZ-string webpage](http://pieroxy.net/blog/pages/lz-string/index.html) this is explained in great detail:

> - `compress` produces invalid UTF-16 strings. Those can be stored in localStorage only on webkit browsers (Tested on Android, Chrome, Safari). Can be decompressed with `decompress`
> - `compressToUTF16` produces "valid" UTF-16 strings in the sense that all browsers can store them safely. So they can be stored in localStorage on all browsers tested (IE9-10, Firefox, Android, Chrome, Safari). Can be decompressed with `decompressFromUTF16`. This works by using only 15bits of storage per character. The strings produced are therefore 6.66% bigger than those produced by compress
> - `compressToBase64` produces ASCII UTF-16 strings representing the original string encoded in Base64. Can be decompressed with `decompressFromBase64`. This works by using only 6bits of storage per character. The strings produced are therefore 166% bigger than those produced by compress. It can still reduce significantly some JSON compressed objects.
> - `compressToEncodedURIComponent` produces ASCII strings representing the original string encoded in Base64 with a few tweaks to make these URI safe. Hence, you can send them to the server without thinking about URL encoding them. This saves bandwidth and CPU. These strings can be decompressed with `decompressFromEncodedURIComponent`. See the bullet point above for considerations about size.

In case you're wondering why you would want to compress to a URI-safe string: I used it in the Loom Viewer web app to save its state in the URL, meaning people could link to it directly. Compare [these](http://loom.linnarssonlab.org/dataset/cells/osmFISH/osmFISH_SScortex_mouse_all_cells.loom/NrBEoXQGmAGHgEYq2kqi3IExagZjwBYI0R58oA7AVwBs6UMnt5FZ5gB2J1GADl6kYOIr2bxWUIpx7w~wQfOHLmuNODQVpUbE35aEyBckwjdeQmThNaDJsd1sOMeSkPLobvm2HBKdoyUwIHU9IyIYogAnGH2oaHwoYjI~EnhcYzJetgArLo4AGyZJYFeGKRAA) [two](http://loom.linnarssonlab.org/dataset/cells/osmFISH/osmFISH_SScortex_mouse_all_cells.loom/NrBEoXQGmAGHgEYq2kqi3IExagZjwBYI0R4iMUr5t5FZ5gBOa1GBt0mefKAOwCuAG2HVkteoxit47JHJTc50WtzCQeBKJWzUAHGibp5yTByi4LhMnGpDR46nQzS7KrStVdx6vg7E~YACBETFESkRWEJiw~zjEZHx4WMcQxD1sAFZLHAA2ULS4gO9MCCA) links to the same dataset.

**Comment by JobLeonard** [comment]
I assume this answers your question, but don't hesitate to ask if it doesn't!

**Comment by ivanquirino** [comment]
Thanks for the answer. I haven't understodd yet, if I were to send the compressed string as text/plain the the request body and this text won't be used in URIs,  would I use `compress` or `compressToUTF16`? It seems to me that `compressToUTF16` is the best option to keep enconding consistent between clients and servers.

Thanks agains for the answer

**Comment by JobLeonard** [comment]
Yes, use `compressToUTF16`. If you use `compress` it includes control characters (the first 32 items on the ASCII table), which will cause problems.

**Comment by ivanquirino** [comment]
Nice, thanks for the answer!
