### ISSUE TITLE
Relicense as MIT (or alternative)

### ISSUE THREAD

**Issue by iamphill** [pieroxy/lz-string#119]
WTFPL was rejected by the OSI (https://opensource.org/minutes20090304) and can discourage people from using the library. A good alternative would be to relicense as MIT (or something similar).

**Comment by JobLeonard** [comment]
Seems sensible to me. MIT is probably the easiest option since it's the most well-known "do whatever you want, but we're not to blame"-license. 

But as a formality I'd like to hear the opinion of all the current maintainers, including @pieroxy because it's originally his baby ;)

**Comment by Rycochet** [comment]
My vote is for MIT too - doesn't make any real difference to licensing, just officially supported.

**Comment by pieroxy** [comment]
Agreed. MIT looks good to me.

**Comment by rquadling** [comment]
Is https://creativecommons.org/publicdomain/zero/1.0/ a "better" option?

**Comment by JobLeonard** [comment]
I love Creative Commons, but I believe that this is more intended for creative works like art, music, etc.

MIT license also has the benefit of legal precedents in software licensing, I don't know if that is true for CC so people are more confident things are OK when they see it.

**Comment by aaronloe** [comment]
I need to know pretty soon if this is going to happen. If @pieroxy is committed to WTFPL that's fine, I'll just have to find something else.

**Comment by whitehotlogic** [comment]
^^^ this

**Comment by JobLeonard** [comment]
Done. @pieroxy, I added you as the copyright holder since 2013 since that's also what is written in the code.

**Comment by pieroxy** [comment]
Perfect, thanks.

**Comment by pieroxy** [comment]
I just updated the external page to reflect this change: http://pieroxy.net/blog/pages/lz-string/index.html
