### ISSUE TITLE
Please republish with MIT license

### ISSUE THREAD

**Issue by morfey13** [pieroxy/lz-string#147]
Could you please republish lib to npm with MIT license: we can't use lib with [WTFPL license](https://www.npmjs.com/package/lz-string)

**Comment by Rycochet** [comment]
For now install from the github repo directly - the version is identical, so we can't just publish the same version again.

`npm install https://github.com/pieroxy/lz-string.git`

I'm hoping to get some time to convert this over to Typescript soon which will necessitate a bump (but otherwise should be identical).

**Comment by Throttle** [comment]
@Rycochet, in this case could you please publish 1.4.5 with MIT license?

**Comment by Rycochet** [comment]
@Throttle I've not personally got access for that - in legal terms the license is stated in the repo and npmjs is not a source of truth for that - if your automated tools need the correct license then use the github install as stated above

**Comment by revelt** [comment]
CC @pieroxy do you still have the npm publishing rights?

**Comment by pieroxy** [comment]
I should, yes. I'll see what I can do.

**Comment by Conciergerie-Iskills** [comment]
> Could you please republish lib to npm with MIT license: we can't use lib with [WTFPL license](https://www.npmjs.com/package/lz-string)

That said, I'd be interested to understand why you cannot use the code with the WTFPL. The WTFPL is literally the most permissive license of them all, since you can do what you want. So just take it and relicense it as MIT if you want.

**Comment by pieroxy** [comment]
> Could you please republish lib to npm with MIT license: we can't use lib with [WTFPL license](https://www.npmjs.com/package/lz-string)

That said, I'd be interested to understand why you cannot use the code with the WTFPL. The WTFPL is literally the most permissive license of them all, since you can do what you want. So just take it and relicense it as MIT if you want.

**Comment by Rycochet** [comment]
> That said, I'd be interested to understand why you cannot use the code with the WTFPL. The WTFPL is literally the most permissive license of them all, since you can do what you want. So just take it and relicense it as MIT if you want.

There's actually a really good reason - the WTFPL is *not* OSI / open-source compatible according to lawyers - https://opensource.org/licenses/alphabetical - which means that many companies (such as mine) need to specifically discuss what to do (there are libraries out there that can say "yep, this package is OSI compatible so we're good to use it")

**Comment by revelt** [comment]
@pieroxy `lz-string` is a great package, it is still going strong after those years (which proves your skill). It would be unethical for us users to grab it and relicence. Maybe it would make sense to arrange a co-maintainer, somebody who would help with daily maintenance, releases etc? Many popular packages are maintained by multiple people.

**Comment by pieroxy** [comment]
I'll publish the lib with the MIT license this weekend. Thanks for the link to the OSI.

**Comment by eps1lon** [comment]
> I'll publish the lib with the MIT license this weekend. Thanks for the link to the OSI.

@pieroxy The [release on NPM](https://www.npmjs.com/package/lz-string) is still marked as licensed unter WTFPL. Did you publish it somewhere else?

**Comment by pieroxy** [comment]
It looks like I am locked out of npmjs. Cannot log in, cannot change my password (looks like something unexpected occurred! when trying) so as of right now, I am trying to get access back to npmjs. I'll let you know when things move forward.

**Comment by pieroxy** [comment]
Allright, I am back in. Anyone has any idea how to change the license in npmjs? Should I just release a new version with the only change being the license ?

**Comment by pieroxy** [comment]
Thanks a bunch, will do that.

**Comment by pieroxy** [comment]
Allright, I am ready to push it. I'll do that this weekend because if I do something stupid (happened before) I will really not be able to react much in the next couple of days. Expect that early saturday UTC.

**Comment by pieroxy** [comment]
There we go. v1.5.0 is live with MIT license. Thanks for the help!
