### ISSUE TITLE
Can you provide a demo for string-to-string decompression?

### ISSUE THREAD

**Issue by hsluoyz** [pieroxy/lz-string#150]
I saw the nice demo here: https://pieroxy.net/blog/pages/lz-string/demo.html but it doesn't support decompress a string:

![image](https://user-images.githubusercontent.com/3787410/114667138-af017a00-9d31-11eb-9118-9c80da51e5dc.png)

**Comment by pieroxy** [comment]
How did you get that String ? It looks like a Base64 string, the demo page is meant to compress with compressToUTF16 and represent the data in hexadecimal form. Try to input a short string in the top box and hit compress. You will be able to decompress that.

**Comment by hsluoyz** [comment]
@pieroxy that string is encoded from this function:

```js
export function lzStringEncode(str) {
    return LZString.compressToEncodedURIComponent(str);
}
```

Is it possible to decode it in the online demo?

**Comment by pieroxy** [comment]
Not as of now from the UI. What you can do is press `F12` when on the demo page and call LZString directly. For example:

```js
LZString144.compressToEncodedURIComponent("blah blah");
"EYGwhgFgBKlA"
LZString144.decompressFromEncodedURIComponent("EYGwhgFgBKlA");
"blah blah"
```

**Comment by hsluoyz** [comment]
@pieroxy yes, it works!

Can you put this function into the UI?

**Comment by pieroxy** [comment]
I can sure do that, yes.
