### ISSUE TITLE
Specific string seems to break algorithm

### ISSUE THREAD

**Issue by rubixibuc** [pieroxy/lz-string#151]
Compressing "http://apple.com" and then decompressing it returns null instead of the original uncompressed string.

Confirmed behavior on the demo page.

**Comment by pieroxy** [comment]
Did you figure out what was wrong?

**Comment by rubixibuc** [comment]
> Did you figure out what was wrong?

This string definitely broke my service, but because I was using .compress(). Something about the way it compressed the string prevented Redis from being able to save and retrieve it as a key value. Once I switched to the UTF16 version it worked.

**Comment by pieroxy** [comment]
Thanks for the info. I need to make the doc clearer.
