### ISSUE TITLE
Does `compressToUint8Array()` output smaller than `compress()` ?

### ISSUE THREAD

**Issue by shezhangzhang** [pieroxy/lz-string#163]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/26793777/195984998-b31168f3-d7ed-40f8-ae0a-bd1c188fda50.png">

I want to compress the http request body and transfer less size. which one is better to do that? Thanks!

**Comment by Rycochet** [comment]
They'll make identical size as they're both binary - the difference will purely be in the code needed to send them - internally JS might treat them slightly differently, but that's not something you should worry about (and if you did packet sniffing they'd give you identical data)
