### ISSUE TITLE
License Inconsistencies

### ISSUE THREAD

**Issue by karnthis** [pieroxy/lz-string#188]
This project currently lists 2 different licenses depending on where you look.

The "LICENSE" flie has a standard MIT license dated 2013, and this is supported by "MIT" as the license type in the package.json.

The project index page however, which is the authoritative entry point to the project includes the following:

// Copyright (c) 2013 Pieroxy <pieroxy@pieroxy.net>
// This work is free. You can redistribute it and/or modify it
// under the terms of the WTFPL, Version 2
// For more information see LICENSE.txt or http://www.wtfpl.net/
//
// For more information, the home page:
// http://pieroxy.net/blog/pages/lz-string/testing.html
//
// LZ-based compression algorithm, version 1.4.5

This block of text has 3 primary issues.
- It has the same year as the MIT, so it is not clear which is the current license.
- LICENSE.txt does not exist.
- http://www.wtfpl.net/ does not load, and is generally considered a tongue-in-cheek non-license.

I propose MIT is made the authoritative license and all references to others are updated to align.

**Comment by Rycochet** [comment]
Already on this - we're under the MIT, and I need to go through and add a file header to everything and correct anything wrong - but thank you for creating a ticket for me to track it!

**Comment by Georg-Git** [comment]
Thank you for this library!!!

But this issue is not solved completly 🤣

lz-string.js
```
...
under the terms of the WTFPL, Version 2
...
LZ-based compression algorithm, version 1.4.5
```

**Comment by Rycochet** [comment]
@Georg-Git Where is that file in the repo? 👀

**Comment by Georg-Git** [comment]
https://github.com/pieroxy/lz-string/archive/refs/tags/1.5.0.zip

lz-string-1.5.0.zip:
lz-string-1.5.0/libs/lz-string.js

**Comment by Rycochet** [comment]
@Georg-Git That's not in the source, it would be inside `https://github.com/pieroxy/lz-string/blob/` if it was - that's historical versions, and you cannot retrospectively change the license on them.
