### ISSUE TITLE
Performance Tweaking

### ISSUE THREAD

**Issue by Ixonal** [pieroxy/lz-string#33]
I'm looking through the code, trying to find any way to speed it up even more. I think I found one way (at least for browsers that need it, like IE). I see a lot of loops that use the string's length. Some browsers will recalculate that on each read, so it would speed things (slightly) up to set a local variable to be the input's length and then just reference that, instead of the property itself. Also, in compressToBase64, the while loop is testing against length * 2, which will have to be recalculated each time, so a local variable would help there too. 

Also, great lib. Using it to store a rather large bit of state information in local storage with no (as far as I've seen) issues.

**Comment by Ixonal** [comment]
Alright, made a jsperf for it. The results seem about even, though I have IE11, so I'm not sure if this is really accurate, but it's slightly faster in IE9 mode, and a lil bit faster than that in IE8 mode. 

http://jsperf.com/lz-string-performance-enhancement-test

**Comment by pieroxy** [comment]
Thanks for the jsperf. These changes seem to be slightly beneficial to some browser while neutral to others (slightly negative for IE8 but it's IE8 so I quite don't care). In other words it looks good. I'm waiting until tomorrow in order to be able to test this on Windows to make sure I can't find a browser with a negative impact.

**Comment by pieroxy** [comment]
Ah, my bad, I was reading the JSPerf backwards... So it looks like your changes are faster on IE8, neutral on IE>8 and Firefox but slower on Chrome and Safari. Doesn't look good... Unless I'm mistaken once more that is ;-)

**Comment by Ixonal** [comment]
well, the changes were meant to be of benefit to older engines. newer ones are fast enough that it doesn't really matter that much. actually, IIRC, chrome is optimized to handle loops based on string/array length more efficiently. Though, I began wondering after the fact if string length is ever actually recalculated. strings should be immutable, so there'd never be a need to recalculate it like an array does...

**Comment by pieroxy** [comment]
Did you change something on the jsperf? Results are very different this morning... The modified code runs consistently faster than the original one on pretty much all platforms...

**Comment by Ixonal** [comment]
I haven't changed anything to either the jsperf or the library since I posted it. Odd that it should choose to act differently.

**Comment by ChALkeR** [comment]
The modified version is 24% slower for me on Chromium 40.

**Comment by Ixonal** [comment]
interesting. I'm not sure how it would've had that much of an effect in any browser, either positive or negative.

**Comment by ChALkeR** [comment]
Maybe that's because you are using the master version of lz-string and it got updated?

**Comment by Ixonal** [comment]
Admittedly, I haven't messed with this since the original conversation. It's probably irrelevant at this point.

**Comment by pieroxy** [comment]
Closing this issue. The performance gain wasn't clear or significant and we're going to move toward greater gains with ES6 stuff for newer browsers
