### ISSUE TITLE
Broken in Firefox 

### ISSUE THREAD

**Issue by barneycarroll** [pieroxy/lz-string#35]
I've got a fairly contrived use-case whereby I am using the URI-safe base64 methods to encode URI-encoded URIs (my SPA uses the browser history API to produce completely RESTful URIs and every significant action modifies the URI and then decodes it to infer application state: the result is that any application state is bookmarkable and shareable).

In this scenario, the core decompression method always returns `null` using Firefox (everything behaves as expected in Chrome, the only other environment I've tested with any rigour).

After a bit of stepping through, it appears the core decompression loop always manages to reconstruct part of the string, but always eventually encounters a failure switch case and returns `null`. I suspect certain characters or substrings are to blame and I will try to isolate these for a reduced test case.

**Comment by pieroxy** [comment]
Base64 output is not URL safe. The doc light have been misleading in this. I created a new method in the latest release: compressToEncodedURIComponent. This one is less ambiguous. Give it a try and let me know.

**Comment by barneycarroll** [comment]
That's the one I'm using — it was me who requested that feature ;)

**Comment by barneycarroll** [comment]
False alarm. This had to do with Firefox auto-decoding URI components on read and intermediary software performing its own unwanted replacements.

**Comment by pieroxy** [comment]
Thanks for the update.
