### ISSUE TITLE
Add bower.json file

### ISSUE THREAD

**Issue by maxiruani** [pieroxy/lz-string#36]
Could you add the project to bower?
Thanks in advance

**Comment by pieroxy** [comment]
I've added bower.json. I did a register and it told me a bunch of garbage such as:

invalid-meta lz-string is missing "main" entry in bower.json (even though it is there)
invalid-meta lz-string is missing "ignore" entry in bower.json (it is there as well)
EDUPLICATE Duplicate package

I did bower install lz-string and it worked...

Can you check to see if everything is working?

**Comment by maxiruani** [comment]
I have tested. I can install the package, but ./libs folder is missing.
Maybe you just haven't pushed the git tag.
[Check this out](http://stackoverflow.com/questions/19456091/bower-register-new-version)

**Comment by maxiruani** [comment]
I have just realized that int the bower.json file the version detailed is "1.3.5" and the current one is "1.3.6"

**Comment by pieroxy** [comment]
Do I have to re-register after modifying the json ?

**Comment by pieroxy** [comment]
There, I fixed it.

**Comment by maxiruani** [comment]
Excellent, thanks!
