### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by pablote** [pieroxy/lz-string#37]
What's the browser support for this lib? I couldn't find any info on the web site. Or at least what js features does it use? so I can look it up, and also possibly for polyfills. Thanks.

**Comment by pieroxy** [comment]
It works on IE6 and up, all versions of Firefox, Chrome, Safari, Opera and other browsers I could get my hands on. Unless you use convertToUint8Array, it just uses strings, numbers and stuff that have been in all browsers for decades. I'll add it in the doc.

**Comment by pablote** [comment]
That's awesome. Thank you.

**Comment by pieroxy** [comment]
I added something in the doc.
