### ISSUE TITLE
License.txt

### ISSUE THREAD

**Issue by AndyF** [pieroxy/lz-string#40]
[wat](https://github.com/pieroxy/lz-string/blob/master/LICENSE.txt)

**Comment by pieroxy** [comment]
What wat ?

**Comment by pieroxy** [comment]
Note that the license was approved as a GPL-compatible free software license by the Free Software Foundation. It's all that matters, right?

**Comment by AndyF** [comment]
Link to FSF approval?

**Comment by tmedwards** [comment]
One Google later….  It's anecdotal, but what you're looking for is under the *Is the WTFPL a valid license?* section of the [WTFPL FAQ](http://www.wtfpl.net/faq/ "http://www.wtfpl.net/faq/").

**Comment by pieroxy** [comment]
I was thinking of the wikipedia page for the license: http://en.wikipedia.org/wiki/WTFPL

As everyone knows, wikipedia is the ultimate holder of all truth.

If you still doubt it, well, you just can do what the fuck you want to, so you can ultimately relicense it with the license you see fit. That way you'll have the license you chose and that should be good enough.
