### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by thejae** [pieroxy/lz-string#41]
Am just wondering about the feasibility of adding some form of passphrase protection. Am well aware that it's a relatively weak form of protection but increasing the level of obfuscation even by a tiny bit could be helpful in slowing/ deterring would-be crackers.

**Comment by pieroxy** [comment]
I guess you are thinking about encryption. If it's possible for your webpages to decrypt the data, it probably means that there is enough information on the client side to decrypt it, so there is probably little purpose for this... If that's what you're looking for.

In any case, there are already good libraries out there for this: http://code.google.com/p/crypto-js/ comes to mind first. It can encrypt anything given current state-of-the-art algorithms. I suggest you process the output of lz-string with the CryptoJS algo that suit your need.

The purpose of lz-string is to compress and store efficiently. It's far from perfect on that front, so I'll focus on that for now.
