### ISSUE TITLE
decompressFromUint8Array test failing on Safari 8.0.3

### ISSUE THREAD

**Issue by carlansley** [pieroxy/lz-string#42]
Thanks for the nice library!   But while packaging up a version for Angular (https://github.com/carlansley/angular-lz-string) I noticed a test was failing in Safari.  The issue is the apply is failing.  Patched the my angular version to use forEach instead.

Failing 1 spec
37 specs | 1 failing
LZString uint8array compresses and decompresses all printable UTF-16 characters.
RangeError: Maximum call stack size exceeded. in file:///Users/carl/Development/lz-string/libs/lz-string.js (line 263)
decompressFromUint8Array@file:///Users/carl/Development/lz-string/libs/lz-string.js:263:61
file:///Users/carl/Development/lz-string/tests/lz-string-spec.js:69:38
execute@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:1064:22
next_@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2096:38
start@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2049:13
execute@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2376:19
next_@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2096:38
start@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2049:13
execute@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2521:19
next_@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2096:38
onComplete@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2092:23
finish@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2478:15
file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2522:16
next_@file:///Users/carl/Development/lz-string/tests/lib/jasmine-1.3.1/jasmine.js:2106:24

**Comment by carlansley** [comment]
In decompressFromUint8Array, replacing:

        return LZString.decompress(String.fromCharCode.apply(null, buf));

with:

        var result = "";
        buf.forEach(function (c) {
          result += String.fromCharCode(c);
        });
        return LZString.decompress(result);

resolves the issue.

**Comment by pieroxy** [comment]
Thanks for the fix !
