### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by efusien** [pieroxy/lz-string#45]
On IE11 we can save a compressed string to localStorage.
But if we refresh the page, the data is not present anymore in the localStorage.

Seems caused by special caracters. Some caracters fail the storage.
This caracter breaks : ؁

This is working :
    ঄〮⁜ॠ똠猂頞耎ΰ䆸ѢƜ逍耖iꀍ䀡Ǥɐ᷀

This is not working
    ঄〮⁜ॠ똠猂頞耎ΰ䆸ѢƜ逍耖iꀍ䀡Ǥɐ᷀؁ꐇ၀笁

**Comment by efusien** [comment]
Ok, using these methods seems to work well:

LZString.compressToUTF16
LZString.decompressFromUTF16

Source: http://pieroxy.net/blog/pages/lz-string/guide.html

**Comment by webdeveloperneeraj** [comment]
LZString.compressToUTF16
LZString.decompressFromUTF16
For IE these are not compress the data.It's works fine in chrome.

**Comment by rquadling** [comment]
LocalStorage is finite in size. Pretty much nothing this library can do about that. Put less data into LocalStorage is really the only feasible option.
