### ISSUE TITLE
Make compressToEncodedURIComponent URI safe.

### ISSUE THREAD

**Issue by maiwald** [pieroxy/lz-string#50]
Hey there,

unfortunately we recently discovered a bug where we would compress data, append it to a URI and then be unable to decompress it after parsing the url because the compressed string contained  `+` characters which were interpreted as whitespace.

When you check the [base64url standard](http://en.wikipedia.org/wiki/Base64#Variants_summary_table), the `_keyStrUriSafe` map, should actually be 
```
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_="
```
without the `+` character. In fact  `+` is a reserved character in URIs ([RFC3986](https://tools.ietf.org/html/rfc3986#section-2.2)).

I wanted to write a pull request but was uncertain about the consequences for backwards compatibility.
Is there anything I can do to help?

Cheers

**Comment by pieroxy** [comment]
In the meantime, you can still replace all spaces by + characters...

I'll think of something.

**Comment by pieroxy** [comment]
I've just released v1.4.2 that adresses your problem. Can you have a look and tell me if it works for you ?

If it doesn't I'll close the issue.

Thanks for the bug report.

**Comment by maiwald** [comment]
I think URL-safe-compression should rather comply with the standards but this is better than nothing, I guess.

Thanks!

**Comment by pieroxy** [comment]
If there was one standard, I'd agree with you. But with 13 standards...

**Comment by maiwald** [comment]
As far as I see it, there is only on when it comes to URIs: http://tools.ietf.org/html/rfc4648#section-5

**Comment by pieroxy** [comment]
I guess it's too late now... While the method is based on base64, nothing in its contract specifies it's going to output base64, so I think it's no big deal. Except for the ugly hack that is... :-/

**Comment by maiwald** [comment]
yup, totally agree. It works now, so thanks! :)
