### ISSUE TITLE
JSON Response Performance

### ISSUE THREAD

**Issue by micahlisonbee** [pieroxy/lz-string#55]
I have a JSON response, about 700,000 characters. I stringify it, then compress. The compression takes about 11s.

However, when I paste that same stringifed text into a textbox, grab the .value, then compress, it only takes about 1s.

Any idea why?

**Comment by pieroxy** [comment]
My first guess is that the extra 10 seconds are spent outside the compression. Can you make a jsfiddle out of it so that I can see your code in action?

**Comment by micahlisonbee** [comment]
I have a jsfiddle that grabs data from a source and then compresses it.

One of the URLS (static json file) compresses very quickly (< 1000ms).
The dynamic url compresses much slower (~7500ms).

Switch between the two URL variables to see the difference.

http://jsfiddle.net/theur7nd/2/

Thanks for your help.

**Comment by pieroxy** [comment]
I've slightly modified your jsfiddle to add the size of the input: http://jsfiddle.net/u52ujty5/

What I see from my computer (Chromium - Linux) :
  * With `dynamicEndPoint`: `Done in: 508 for 867331 bytes`
  * With `staticJSONFile`: `Done in: 507 for 785159 bytes`

This looks pretty reasonable to me... Firefox exhibits the same behavior.

What is the config you're using? (OS/browser)

**Comment by rquadling** [comment]
OOI, the URL for the dynamic end point has ?time=?time= ... I assume that this has no effect.

**Comment by micahlisonbee** [comment]
I see similar results now as well.

Thanks for your time on this. You know, our API team actually updated the dynamic response within the last few days and now instead of 30s, it's almost instant, I think when it was taking 30s to pull the response, that's when the compression was taking 10s longer, not sure why.

**Comment by pieroxy** [comment]
Allright, thanks for the feedback.
