### ISSUE TITLE
Demo LZ decompress did not work... 

### ISSUE THREAD

**Issue by jcalfee** [pieroxy/lz-string#56]
In the demo (http://pieroxy.net/blog/pages/lz-string/demo.html), after compressing the readable text, clicking on the LZ decompress button causes does not re-populate the readable text.

**Comment by pieroxy** [comment]
You're right. I have screwed up something in there. I'll look into it tomorrow. 

Thanks.

**Comment by pieroxy** [comment]
There. Not perfect yet, but it's working.
