### ISSUE TITLE
save compressed data to MongoDB, can't be decompressed again

### ISSUE THREAD

**Issue by eisneim** [pieroxy/lz-string#58]
Hi, my app need to compress some svg code and save them into MongoDB using Mongoose,  save as String or Buffer neither of them will work!  the decompress all return null; the output of comressed string and mongodb string are same string,same length.
 i checked lz-string code and here is some info: 
```javascript
// from line 468
if (dictionary[c]) {
        entry = dictionary[c];
      } else {
        if (c === dictSize) {
          entry = w + w.charAt(0);
        } else {
          console.log(c)
          console.log( dictionary )
          console.log( result )
          console.log( entry )
          console.log("__can not decompress? but why?__")
          return null;
        }
      }

// and herer is the log message: 
31
[ 0,
  1,
  2,
  '<',
  's',
  '<s',
  'v',
  'sv',
  'g',
  'vg',
  ' ',
  'g ',
  'x',
  ' x',
  'm',
  'xm',
  'l',
  'ml',
  'n',
  'ln',
  'ns',
  '=',
  's=',
  '"',
  '="',
  'h',
  '"h',
  'ô',
  'hô' ]
[ '<', 's', 'v', 'g', ' ', 'x', 'm', 'l', 'n', 's', '=', '"', 'h', 'ô' ]
ô
__can not decompress? but why?__
```
is mongodb changed some of binary data? or is it a lz-string's bug?
if anyone knows how to solve this problem, great thanks.   

or, is save gziped data to mongodb is a better choice?

**Comment by pieroxy** [comment]
First, have a look at this (very similar) issue which could probably solve your problem: [https://github.com/pieroxy/lz-string/issues/57]

lz-string is a hack that consts in storing binary data in a String. I only produce valid UTF-16 but maybe a text field in MongoDB is not accepting ALL characters.

The best way to troubleshoot is to compare the string you're storing to the string you're retrieving. My guess is that they are different in some way. Some UTF processing replaces characters with others deemed "equivalent". Of course, since lz-strnig uses it as a bitstream, it destroys the input.

**Comment by eisneim** [comment]
@pieroxy thanks

**Comment by tracker1** [comment]
It might be worth filing an issue with the mongo driver you're using, it's likely that the strings are being normalized (as @pieroxy mentioned) many characters can have multiple representations, and this may be a path taken to improve indexability.

Also, mongodb as of 3.0 supports compression, including zlib at the database level, so you should probably just store it from the buffer as a blob/binary... IIRC the node mongo interface should handle Buffer's

**Comment by eisneim** [comment]
thanks for your info @tracker1

**Comment by ShaneOH** [comment]
Just want to bump here that I had the same issue with MongoDB here and maybe it's related to those "invalid" UTF-16 characters. Switching `compress` to `compressToUTF16` and same for decompress fixed this for me

**Comment by pieroxy** [comment]
As the documentation states, compress and decompress produces invalid UTF-16 strings, so there is no guarantee a storage system will output its input unchanged.
