### ISSUE TITLE
Firefox silently corrupts LZString encoded data on browser restart.

### ISSUE THREAD

**Issue by sj4nz** [pieroxy/lz-string#59]
Firefox `localStorage` works great with this compression scheme, until you restart the browser. When the browser restarts, it seems that the reloading mechanism silently changes bytes resulting in data corruption. If you're experiencing maddening corruption issues when Firefox restarts with your localStorage data, this is why. If you always clear your `localStorage` you'll never see this bug.

An example from my debugging output, the "RESTORED" data (data put in localStorage after a browser restart) is 442 bytes, here shown in hexadecimal, the base36 number that follows after the ! is the sum of the row and the one at the bottom of the column is the sum of the column, I used these just to help me identify which data was changed without going blind. The original data prior to compression is just JSON.

The "CHK" data is the original data saved before the browser restarted. There are two errors in the restored data in the second to last row (yg in RESTORED, uw in CHK) in columns 6 and 8. `d9 cf df ad` has become `dd cf 5b ad`.

```
"RESTORED" 442 
 82 37 7a 20 5c 20 c0 08 0c 2c ! jz
 36 c0 72 02 ac 20 03 d0 90 35 ! r2
 44 26 42 03 54 00 40 51 00 07 ! bf
 6a 46 09 c0 b2 8d 4a 5b 19 03 ! op
 3b 60 97 26 bc 4b 9a 01 27 67 ! p4
 8e d6 2c 34 05 f8 e0 33 da 10 ! xq
 5c 39 62 95 04 61 00 40 48 99 ! lu
 5b b8 e7 73 0b 93 e5 09 48 a7 ! yw
 9a 9c 34 0b 13 d9 cf df ad 1c ! yg
 35 64 a7 a1 9a eb 72 7e 02 20 ! vs
 00 f9 
----------------------------------
 0d 07 0a 0z 07 00 01 0y 01 0u 

" app.js:63:172
"CHK" 442 
 82 37 7a 20 5c 20 c0 08 0c 2c ! jz
 36 c0 72 02 ac 20 03 d0 90 35 ! r2
 44 26 42 03 54 00 40 51 00 07 ! bf
 6a 46 09 c0 b2 8d 4a 5b 19 03 ! op
 3b 60 97 26 bc 4b 9a 01 27 67 ! p4
 8e d6 2c 34 05 f8 e0 33 da 10 ! xq
 5c 39 62 95 04 61 00 40 48 99 ! lu
 5b b8 e7 73 0b 93 e5 09 48 a7 ! yw
 9a 9c 34 0b 13 dd cf 5b ad 1c ! uw
 35 64 a7 a1 9a eb 72 7e 02 20 ! vs
 00 f9 
----------------------------------
 0d 07 0a 0z 07 04 01 0a 01 0u 
"
```

From https://en.wikipedia.org/wiki/UTF-16#U.2B10000_to_U.2B10FFFF it appears that 
0xD800..0xDBFF and 0xDC00..0xDFFF are the values to avoid (at least on Firefox) but if you're
going to share compressed data between browsers, these values should be considered toxic.

**Comment by pieroxy** [comment]
Can you tell me which method you used to encode your data? (eg: `LZString.compress` or `LZString.compressToUTF16` ...) ?

**Comment by sj4nz** [comment]
LZString.compress. Aha, I think you're hinting at something. ;)

On Wed, Jul 15, 2015 at 8:17 AM, pieroxy <notifications@github.com> wrote:

> Can you tell me which method you used to encode your data? (eg:
> LZString.compress or LZString.compressToUTF16 ...) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pieroxy/lz-string/issues/59#issuecomment-121611784>.
>



-- 
Simon Ja*n*es

* <simon.janes@gmail.com <simon.janes@gmail.com>>*

**Comment by pieroxy** [comment]
Yes, a kind RTFM: http://pieroxy.net/blog/pages/lz-string/guide.html

**Comment by sj4nz** [comment]
Definitely.  Chrome and Opera will let you get away with it. But not
Firefox.

On Wed, Jul 15, 2015 at 8:22 AM, pieroxy <notifications@github.com> wrote:

> Yes, a kind RTFM: http://pieroxy.net/blog/pages/lz-string/guide.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pieroxy/lz-string/issues/59#issuecomment-121614313>.
>



-- 
Simon Ja*n*es

* <simon.janes@gmail.com <simon.janes@gmail.com>>*
