### ISSUE TITLE
Base64 issue, lz-string.js -> lz-string-php

### ISSUE THREAD

**Issue by CityofStw** [pieroxy/lz-string#62]
Have run into an issue when using the compressToBase64 from lz-string.js and then trying to use the decompressFromBase64 from lz-string-php https://github.com/nullpunkt/lz-string-php  I have tried 1.4.4 and 1.5 Beta - both seem to handle Base64 the same.  The PHP is what is current at the link above.

Most of the time it is fine, but on some strings it fails.  Think I have tracked it down to how the Base64 is done.  Appears for the PHP support has been added for extended characters which is causing the issues.

In testing, found a simple sample.  "ABC".

Compress it with JS and I get: IIIQwkA=
Compress it with PHP and I get: IIIQwkAA

The result from PHP will decompress in PHP or JS just fine.  The result from JS will decompress in JS but causes the PHP code to throw an error.

My original sample was a much larger string, but the ending of each was similar.  JS ended with A== and the PHP ended with AA=.

Any thoughts on adding extended character support to lz-string.js?

**Comment by ValentinH** [comment]
Same issue here with the python-version: https://github.com/gkovacs/lz-string-python

**Comment by pieroxy** [comment]
It looks as if the PHP and python versions don't produce the correct string (and can't parse it either.) Wouldn't it be easier and cleaner to fix the PHP and python version?

**Comment by CityofStw** [comment]
From what I can tell, both the PHP and Python versions support UTF8 on the (de)compressToBase64 functions, which is where the difference seems to stem from.  So it is either remove that support from those, or add it to the JS version.

**Comment by CityofStw** [comment]
Oddly enough, if you go back to version 1.3.7 of the JS, the To/From Base64 functions match what is in PHP and Python.  So far that seems to have resolved my problem, still testing though.

**Comment by pieroxy** [comment]
Ah, I see, you're right. Version 1.3.8 did introduce a change in how the Base64 is generated, introducing small changes. It is fully compatible both ways with the JS version (all versions can decompress the result of all versions).

But I didn't think of the various ports.

So you're completely right: version 1.3.7 of the JS library will fix your problem.

I'll look into the various ports and apply the proper fixes in the coming days.

**Comment by rufushuang** [comment]
Glad to see this issue?

pieroxy you really found out the porting version incompatible problem, which cause me some trouble when I port 1.4.4 version to java. https://github.com/rufushuang/lz-string4java

So, what's your opinion if one want to port a version with Base64 and uri support?
Or some version compatible hint or so?

**Comment by pieroxy** [comment]
I am going to rewrite a reference implementation (https://github.com/pieroxy/lz-string/blob/master/reference/lz-string-1.0.2.js at the moment) which will include the newer base64 routine. This is the version you're supposed to port whenever porting to any language as mentioned in the doc.

**Comment by netgfx** [comment]
Is this issue resolved with the latest js version and the PHP port?

**Comment by CityofStw** [comment]
I’d found a mixture of versions which worked for me, and haven’t updated.

When I get a chance to revisit, I may try the newest, but not sure when that would be.

Gene Comer
Application Developer & Network Specialist

**Comment by nullpunkt** [comment]
Hi, just to inform you: i rewrote the php implementation to be compatible with current js version (and just to let you know: added composer support and wrote some unit tests to be more stable).

**Comment by SiliconValet** [comment]
Any updates here?

**Comment by pieroxy** [comment]
From what I understand nullpunkt has written a php version that is compatible with the latest release...

What are your expectations?

**Comment by SiliconValet** [comment]
I guess I misunderstood the problem. I thought that the changes introduced in 1.3.8 caused the problems and that nullpunkt had simply worked around it. That appears to be the narrative above.

I wanted the assurance of portability across implementations, which to me means that I've got to use 1.3.7.

**Comment by pieroxy** [comment]
I'm closing the issue as I don't own the various ports of lz-string.
