### ISSUE TITLE
Creates a larger byte string?

### ISSUE THREAD

**Issue by tomekmarchi** [pieroxy/lz-string#63]
dfhjksfhjas fgjdhsaf lSDFHLF ljljkahjdfhaljkhfdlknvjasnfhlHLEUYRIUORWYIUjdkjhafkjdhfhjdafclkj: 
93 characters, 93 bytes
TO
ӡ䰥䃌඀析䄬〡Чᡸメፀᬡ䨠䐣ࠡဦ⩡ਖ䃄僠⽴てྴČǚს眯䕠ᑠᕠ፠ॠቢ⁜䙠㪴䋬⠰ⱡ㖇䘫䀸淢ࠠ: 
44 characters, 128 bytes

**Comment by pieroxy** [comment]
If I try this on my test page : http://pieroxy.net/blog/pages/lz-string/demo.html

Your finput string is actually 186 bytes (not 93 as you mention) and the compressed version is 41 bytes, so roughly 22% of the size of the input.

Remember that ALL strings are represented internally as UTF-16 in JavaScript, so no char takes less than 2 bytes.

**Comment by tomekmarchi** [comment]
var Buffer = require('buffer').Buffer;

console.log(str.length + " characters, " + Buffer.byteLength(str, 'utf16') + " bytes"); //93 characters, 93 bytes
console.log(LZString.compress(str).length + " characters, " + Buffer.byteLength(LZString.compress(str), 'utf16') + " bytes"); //41 characters, 113 bytes

Node doesn't seem to agree, using utf-16...

**Comment by tomekmarchi** [comment]
Looking to use this on the next version of LNKit. Would be advantageous to find out what exactly is going on here. When receiving data nodejs also reports a smaller byte count for the base64 data sent to server rather than the default UTF-16 function. I have a few assumptions but shoot me an email or add me on skype. Looking forward to figuring it out.

**Comment by pieroxy** [comment]
I don't know what Buffer is, nor what Buffer.byteLength(str, 'utf16') does, but it contradicts the specs of unicode. I'll go with the spec. So either the method is buggy, either it's not doing what you think it's doing.

As a matter of fact, try this: Buffer.byteLength("a", "my mother is the best") and tell me what you see. 

This suits well my experience with nodejs. Everything is so buggy that it's borderline unusable.

Anyways, LZString is made FOR THE BROWSER, not for the server. There is no point in encoding anything with LZString in nodejs (at least, not that I know of).

Why don't you start by telling me what you're trying to achieve first ?

**Comment by tmedwards** [comment]
@tomekmarchi The problem is that you are using an invalid encoding name, so `Buffer.byteLength()` is falling back on its default encoding, which is `utf8`.  The correct UTF-16 encoding names are `utf16le` and `ucs2` (alias of the former).  Try the following:
```JavaScript
Buffer.byteLength(str, 'utf16le')
```
You can see this [in the documentation](https://nodejs.org/api/buffer.html#buffer_buffer "https://nodejs.org/api/buffer.html#buffer_buffer").

**Comment by pieroxy** [comment]
@tmedwards I'm sure this beyond-crappy behavior is documented somewhere, which is completely besides the point. How someone can design a piece of code that swallows errors this way is beyond me. Anyways.

To get back to the original point, with "utf16le" the size of the original string is "93 characters, 186 bytes" while the compressed version is be "41 characters, 82 bytes"

So LZString is actually compressing something.

Now, to get back to my original question, @tomekmarchi what exactly are you trying to achieve here?

**Comment by tomekmarchi** [comment]
@tmedwards Good looks.
@pieroxy compression experimentation.
