### ISSUE TITLE
Please change the license

### ISSUE THREAD

**Issue by tucson-tom** [pieroxy/lz-string#64]
The license you are using is not OSI approved.  I can't use your software in our software until there is an appropriate legal disclaimer.  You'll also begin caring a great deal about the license you use if someone decides to sue you using legal terminology such as warranties, merchantability, claims, damages, and/or liabilities where you will have to defend yourself in a court of law and you will most likely lose any such lawsuits.

If an organization interested in your software cares about their legal rear (most do), they can't use your software because using it could drag them into a lawsuit in the event of a catastrophic failure of your software product.  As-is, organizations that do proper legal due diligence will simply avoid your software.

The MIT license is the most liberal OSI approved license that contains the appropriate legalese that protects everyone using your software - including yourself!  Given the current legal landscape, the best option is to cover your butt with a license that has been run through a gauntlet of lawyers.  The MIT license is harmless and much more widely used than the current license of this project.  You should adopt it or any of the other OSI approved licenses.  You can even dual-license the software if you want - that is, give people a choice of which license they wish to license your software under.

**Comment by pieroxy** [comment]
You should read the license once again. You can do whatever the fuck you want. So take the lib, strip the license, slap any license you find convenient on top of it and be done with it.

YOU CAN DO WHATEVER YOU WANT. What more do you want? It rarely get any better than this, trust me.

**Comment by tucson-tom** [comment]
I did read the license.

I understand the intent BUT the law doesn't work the way you imagine.  Since you originally authored the code, you own the copyright on the code but ownership and liability are two separate things in the eyes of the law.  You are still legally liable for the code even if you decide you don't want to claim copyright.  This issue was opened to encourage you to protect yourself as well as anyone using your code.  As it stands, if your code is deemed harmful in any way whatsoever, you can be sued over it and will lose any such lawsuit.  The original recommendation still stands.

**Comment by rquadling** [comment]
I think the issue is that Americans can sue you because they don't have the concept of a frivolous lawsuits. If they do, they've forgotten. On the other hand, a good argument goes something like this "So, you found some free software that came with no merchantability or anything saying it was going to work for you in the way you wanted. You were unable to make it work the way you wanted and so you are going to sue me. Well. Beside being an arsehole, how much did it cost you to use my free software? That is how much I am willing to offer you!".

Oh.... wouldn't it be nice if ... !

Unfortunately, because of the arseholes, you are going to have to use a better license. It's crap. It's stupid. But that's what having a greedy legal system and a lack of common sense and due diligence does for you.

**Comment by tracker1** [comment]
@tucson-tom ISC and MIT are OSI approved licenses, and don't provide any indemnification either... you can think of this as a more permissive ISC-like license...

**Comment by tucson-tom** [comment]
@tracker1 - The issue isn't permissiveness (aka claim to copyright).  The issue is that the existing license is missing important legalese:

(Swiped from the ISC license)
THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL **WARRANTIES** WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED **WARRANTIES** OF **MERCHANTABILITY** AND **FITNESS**. IN NO EVENT SHALL THE AUTHOR BE **LIABLE** FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL **DAMAGES** OR ANY **DAMAGES** WHATSOEVER RESULTING FROM **LOSS OF USE**, **DATA** OR **PROFITS**, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Something like that is necessary to protect all parties involved.  The bolded bits are the things being protected from.  Both the ISC and MIT licenses have a paragraph similar to the above.  The current license of this project does not have such a paragraph.  This is the unfortunate reality we live in.

**Comment by rquadling** [comment]
One change to a part of the license I've seen ... "ARISING OUT OF OR IN CONNECTION WITH THE USE **OR INABILITY TO USE** OR PERFORMANCE OF THIS SOFTWARE".
