### ISSUE TITLE
Submit to JSDelivr CDN

### ISSUE THREAD

**Issue by bradvogel** [pieroxy/lz-string#65]
Would be great to have this on JSDelivr so we can download it with our other scripts (via JSDelivr's concatenation feature).

See https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by pieroxy** [comment]
Will it be of any value for me to do it? I have to say I'm quite tired of adding my lib to the new CDN-of-the-day. If you want to do it, be my guest. You're probably 100% more proficient in JSDelivr than I am and I am sure we will all save some precious time.

If you need me for this, just let me know.
