### ISSUE TITLE
Works on Node but not Google Apps Script

### ISSUE THREAD

**Issue by dancancro** [pieroxy/lz-string#67]
Hi,

I have used this without any problem to compress and decompress a string running in Node.js, but when I send the same compressed string to a Google Apps Script API that I made, and try to decompress it, the same code doesn't work. In that case, decompress returns null. I have verified that the compressed string is the same length at both ends of its trip. Maybe there's something else that happened to it on the trip or Google Apps Script treats characters differently. I'm not sure what else to check.

Do you have any ideas why this might be happening?

Thanks,
Dan

**Comment by pieroxy** [comment]
What do you do with the compressed string ? Do you stored it somewhere ?

**Comment by pieroxy** [comment]
Other ways to investigate: Try with compressToBase64 (and the corresponding decompress method)

**Comment by dancancro** [comment]
All set, thank you.  compressToBase64 gave me the same trouble, but compressToUTF16 worked.
