### ISSUE TITLE
Localstorage tab freeze

### ISSUE THREAD

**Issue by yiwong2001** [pieroxy/lz-string#69]
HI there, I am testing different methods in Lz-string to compress strings and store results to localstorage.

it shows a good result of compression:

Orginal Size of sample is: 148920
Size of compressed sample is: 13349
Size of utf16 sample is: 14240
Size of compressToBase64 sample is: 35600

BUT I noticed local storage tab of Dev tools in chrome would be freezed once I store compressed string produced by methods: compressed/compressToUTF16. There is no issue with compressToBase64. 

Any clue?

Dummy code:

var strings = "........."
var compressed = LZString.compress(strings);
disk.set("key1", compressed);

Thanks

**Comment by pieroxy** [comment]
Some other user had the same issue: http://pieroxy.net/blog/2013/05/09/just_released_lz_string.html#comment1374786831293

It's not frozen, it's just that browsers and UIs in general are pretty awful at displaying stuff that contains the whole range of unicode characters....
