### ISSUE TITLE
Demo Page Hex Incorrect

### ISSUE THREAD

**Issue by koudelka** [pieroxy/lz-string#71]
Hey there,

It looks like the hex output on the [demo page](http://pieroxy.net/blog/pages/lz-string/demo.html) is incorrect. It seems to be swapping pairs of bytes.

For the string `"ab"`, the hex output is `82 21 00 32`, which is `130 33 0 50` in decimal.

Whereas `LZString144.compressToUint8Array("ab")` gives `[33, 130, 50, 0]`.

**Comment by rquadling** [comment]
I think this is the difference between 16bit (2 bytes, little endian) and 8bit displays.

**Comment by pieroxy** [comment]
Well, it's just a demo page. The order of the bytes in a 16-bit word is dependent on the endianness of your machine, so both expressions are correct in their own context...

**Comment by sibvrv** [comment]
Yes, demo page is incorrect.
string: "testing" - Size:14 bytes
LZ-String: 85 0b ce 30 96 c0 60 07 40 e6 - Size:5 bytes 
size must be 10 bytes - 5 chars

**Comment by tcjustin** [comment]
I opened #76 with an example as it looks to me like the demo page always shows half the size that it should for lz-strings byte size.

**Comment by pieroxy** [comment]
Fixed
