### ISSUE TITLE
Weird behaviour with IE & Edge and (possibly) timestamps

### ISSUE THREAD

**Issue by divillysausages** [pieroxy/lz-string#75]
Hi,

I'm using LZString to compress some data to save to localStrorage. An example of the JSON output would be this:

```
var s = LZString.compress( '{"version":1,"data":[{"dayTS":1454716800000}]}' )
```

It seems to compress find, but when I go to set it in LocalStorage, I get `Invalid Argument` exception.

*However*, If I try to compress and set the following:

```
var s = LZString.compress( '{"version":1,"data":[{"dayTS":14547168}]}' )
```

It works fine. 

Do you have any idea why trying to put a compressed timestamp would trigger the error? I'm guessing that the combination triggers a character that IE/Edge don't support, but I'm really just guessing here.

**Comment by pieroxy** [comment]
You should not use `compress` but `compressToUTF16`. The `compress` method produces invalid UTF-16 characters.

Let me know if that fixed it.

**Comment by divillysausages** [comment]
That did the trick! Reading back over your blog post, you actually mention it, so I'm an idiot not to have seen it. 
Thanks!
