### ISSUE TITLE
Demo Page shows half the count of bytes for lz-string vs full count of bytes for LZMA

### ISSUE THREAD

**Issue by mochacoder** [pieroxy/lz-string#76]
It looks to me like the demo page shows half the size for lz-string vs LZMA.  For example if I take the following text off the page and compress it:

"In this demo, you have three textareas and compressions are timed and mesured between lz-string and LZMA level 1. Compressed data is represented in hexadecimal form for better readability. This page is loosely inspired (and partly copy-pasted) from LZMA.JS Advanced Demo."

I get back this for lz-string which it reports as 110 bytes:

83 24 04 b0 e0 02 09 16 ce 60 09 60 4c 81 60 0b
00 7b 80 d1 e8 9e 98 2b 08 50 1b 60 91 b2 13 40
14 b2 80 4c 13 1e 71 13 12 0b 60 22 6e 0c 00 aa
d3 38 06 87 10 3a 6a ec 8a 41 17 99 5c 0e c7 65
4b c3 23 80 10 64 ba 03 00 d7 c0 06 80 17 38 5a
a8 10 00 c1 cc 1c b0 3c 64 00 68 01 90 05 26 08
72 17 ba 72 04 c0 07 60 00 46 4f 18 59 90 56 18
18 49 8c 99 0c 1e 84 06 19 2e 1e 04 9c 8b 91 c8
85 98 9a 1b 8b 58 0c c0 0a dd 0c 95 2a 1f 1d 8c
1e 42 b5 94 18 91 46 95 46 17 07 02 c0 1f 56 05
1f 01 82 98 86 c2 5d 37 01 1d 47 37 3c 1a 86 5f
4c 05 02 00 d3 86 82 aa 67 08 1f 9d 10 87 a4 d3
40 d6 98 12 8f aa c9 8e d7 d9 0a c0 19 40 19 4c
14 d1 9b 83 20 9c 4d 04 17 1d 00 c8

And this for LZMA which it correctly reports at 231 bytes:

5d 00 00 01 00 0f 01 00 00 00 00 00 00 00 24 9b
80 07 43 7d 08 5c 3c 2f d7 41 cd 33 cc c2 a5 e3
3c 20 29 07 57 db f2 6e 8d f8 1f 55 08 86 f4 c7
aa 05 26 c3 84 50 1a 54 e5 b8 9e 63 97 80 18 0d
57 c4 99 c9 8b cf 46 b5 7c 7b 19 9a d4 fc 1e 4d
9b af 0f f5 5f 6e 29 d0 51 1f df 4c 9a 48 05 ac
f7 e6 f9 ab 3c 4e 2b af 6b 04 6d 06 83 91 ee b6
8d 47 2f ae ae 4f 95 13 a9 26 a4 4e 1d 00 cd e6
3f b7 ba 0d 50 3f 61 a9 7c e1 0c ec c3 52 cc 60
e0 d8 7c ba 2f ce 6e 6c 36 65 28 ab 7a 2d 9c 26
cf 0c 5e 2c 2e 65 26 8e 4f 2b 2f aa 94 a5 85 97
0b 68 c1 1b c8 c3 0c 87 c2 44 1a 20 f6 a7 d7 5d
8a 79 03 79 02 b9 c3 e1 9a 4b 66 c5 17 14 e7 7c
9f fa 1f d9 60 f0 57 25 b5 1d 0c ea e8 31 3c 71
f1 8f ff a3 39 52 00

You can see just by looking at the two they are far closer in size than demo page is showing, it appears the demo page is always cutting lz-string size in half. In this example it should show 220 bytes for lz-string.

**Comment by pieroxy** [comment]
Fixed.
