### ISSUE TITLE
Spaces cause decompressFromUTF16 to return null

### ISSUE THREAD

**Issue by Turtlehead91** [pieroxy/lz-string#79]
The following compresses and decompresses just fine.  As soon as I replace a '&nbsp'; with a space, I receive a null value upon return of decompressFromUTF16.

`<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.&nbsp;Nunc cursus egestas ultricies. Aliquam nulla orci, maximus&nbsp;sed consequat vel, pellentesque non purus. Morbi vitae maximus&nbsp;turpis, vitae congue enim. Vestibulum ut nulla mauris.</p>`

I've been testing this out in Chrome, and it took me forever to figure out what was triggering the null return.  I'm compressing a string that I am putting into a JSON object. I am sending that object to the server to be stored. When the JSON object comes back from the server I am pulling the text out and decompressing it. I don't think my AJAX or server side code is affecting this.  But I figured I'd leave my full description here just in case.

I've figured it out.  Looks like some escape characters where being inserted. If anyone else runs into this, I simple JSON.stringified() my string before compressing it and than JSON.parse() my string after I decompressed it to account for escape characters.

**Comment by rquadling** [comment]
LZString operates on a string. Not an object.

```
LZString.decompressFromUTF16(LZString.compressToUTF16('hello'))
"hello"
LZString.decompressFromUTF16(LZString.compressToUTF16('hel lo'))
"hel lo"
LZString.decompressFromUTF16(LZString.compressToUTF16({a:'b'}))
""
```
