### ISSUE TITLE
Mime type and Content-Encoding

### ISSUE THREAD

**Issue by felixsanz** [pieroxy/lz-string#82]
Is `application/x-compress` an appropiate mime type for lz-string?

And what about Content-Encoding? `lz` ?

**Comment by pieroxy** [comment]
There is no standardisation of any body for Lz-string as far as I am aware. So you can basically use the mime type you want. 

The real question I have is why you would need a mine/type for Lz-string content. Can you describe your use case?

**Comment by felixsanz** [comment]
I'm doing server-client communication and also content negotiation

**Comment by pieroxy** [comment]
So, to communicate from the server to the client, why do you use lz-string? Why not just activating the gzip compression of your webserver?

Also, what part does lz-string have in your content negociation ?

**Comment by felixsanz** [comment]
lz-string is more efficient than gzip by a few % :P

I use Accept-Encoding, but i don't know if there is a common practice like lz, lz-string, lzma, or whatever

**Comment by pieroxy** [comment]
I seriously doubt lz-string compresses better than gzip.

lz-string is an adapted version of LZW, meaning is compresses roughly like the command-line utility `compress` does. I assure you it is only better than `gzip` in some very rare corner cases. Gzip is about an order of magnitude better. How did you measure the compression ratios? Do you have an example of a string that would compress better with lz-string than gzip?

**Comment by felixsanz** [comment]
Some html content. In my tests lz-string was faster than gzip and deflate. The winner was brotli but hard to get it in the browser

**Comment by pieroxy** [comment]
Ah, you meant better in the "faster" sense. While lz-string may be faster it will generally produce a bigger output which may end up being slower overall to your client. 

Anyways. You can use the mime type you want for this use case. It's clearly between you and the client and you wrote both pieces of code, so it's between you and you 🙂

**Comment by felixsanz** [comment]
Sorry i don't know why i said faster. I meant smaller in size.

Thanks! Now it's kinda clear. I have read a lot about this stuff in the last 2 days. Apparently i can use whatever i want xD
