### ISSUE TITLE
String Size Issue

### ISSUE THREAD

**Issue by sorb999** [pieroxy/lz-string#87]
If my string size is too large then it is not able to stringify it in C#.

Here is my code

 `JavaScriptSerializer serializer = new JavaScriptSerializer() { MaxJsonLength = 2147483647 }; 

_Result.Content = "Some Large String From Database";
 var json = serializerSerialize(_Result.Content);//
 var compressedString = `LZString.compressToUTF16(json);`
 _Result.Content = compressedString;`

So if my `Result` is beyond `MaxJsonLength ` then it is not able to work..

**Comment by pieroxy** [comment]
I don't really know what to tell you. If your serializer doesn't support strings greater than X then you cannot use it with a string greater than X... 

I fail to see how LZString is involved.

**Comment by sorb999** [comment]
@pieroxy So that means it will not work without serializing it?? Because if length it greater than this then JavaScriptSerializer() fails.

**Comment by pieroxy** [comment]
From what I understand, you have a string that you compress and you try to make it part of a json field. It looks weird. If it is the only field then yes, do not serialize it. You will have to modify your client a. It to not expect json but to use a string that it will decompress directly.
