### ISSUE TITLE
decompressFromUTF16 return null in firefox 

### ISSUE THREAD

**Issue by fishsses** [pieroxy/lz-string#91]
I use `LZString.compressToUTF16` for c# and `LZString.decompressFromUTF16` for javascript in my code, I tested it correctly on the Chrome/Safari, but firefox always return null.
How can I fix it?

**Comment by fishsses** [comment]
I fount problem, thanks.

**Comment by pieroxy** [comment]
Care to share the problem you found? It could help others stumbling on the same issue.

**Comment by fishsses** [comment]
I have the same problem, and I fixed it to call: 
`beforeSend: function (xhr) { xhr.overrideMimeType('text/plain; charset=UTF-16'); }`
http://stackoverflow.com/questions/9724916/utf-16-character-encoding-issue-with-firefox
