### ISSUE TITLE
Issues with devtools

### ISSUE THREAD

**Issue by si-harps** [pieroxy/lz-string#93]
Hi,

Thanks for this superb library - its working and working quick!!

The only issue i have is that chrome dev-tools (not the functionality) slows almost to a halt whilst working with fairly large (200000+ -> 40000 bytes) JSON objects in local storage.

Anyone else having similar issues?

**Comment by tophf** [comment]
That's a bug in Chrome, see https://crbug.com/640657 and https://crbug.com/658525.
You can mitigate the issue to a degree by using [LZipped Local Storage](https://chrome.google.com/webstore/detail/lzipped-local-storage/beicplgjaeliclenmidelkloajghllll) extension.

**Comment by pieroxy** [comment]
I am not the owner of the chrome dev tools. 

Please see here: https://github.com/kriserickson/lz-localstorage-chrome-extension
